[package]
name = "webbuf"
version.workspace = true
edition = "2021"
authors = ["Astrohacker"]
description = "A Rust library for fast base64 and hex encoding/decoding"
license = "MIT"
repository = "https://github.com/astrohackerlabs/webbuf"
homepage = "https://github.com/astrohackerlabs/webbuf"
readme = "README.md"
keywords = ["base64", "hex", "encoding", "performance", "web"]
categories = ["encoding"]

[dependencies]
base64 = "0.22.1"
hex = "0.4"
base32 = "0.5"

[lib]
crate-type = ["cdylib"]  # Required for generating WebAssembly bindings later if needed

[features]
default = ["wasm"]
wasm = ["wasm-bindgen"]

[dependencies.wasm-bindgen]
version = "0.2"
optional = true


